### ISSUE TITLE
Disappearing status list

### ISSUE THREAD

**Issue by ihabunek** [ihabunek/toot#100]
To reproduce:

* open toot curses

![image](https://user-images.githubusercontent.com/482138/56658942-33b5e200-669c-11e9-8dfe-1b451cbaee6c.png)

* press "c" to compose a new toot, status list disappears:

![image](https://user-images.githubusercontent.com/482138/56659010-5fd16300-669c-11e9-8a1c-ab3b885a2dd9.png)

The issue does not occur if the user moves down the status list by pressing `j` before composing a toot.

**Comment by ihabunek** [comment]
This seems to occur when calling getch on text window:

https://github.com/ihabunek/toot/blob/aff0c2281f772d7abd63f35f1f9381c550f7de94/toot/ui/app.py#L447

**Comment by ihabunek** [comment]
@Skehmatics Could you take a look at this issue?

I've also reproduced the same issue by calling `self.stdscr.getch()` instead of `self.left.pad.getch()` in the main loop.

**Comment by Skehmatics** [comment]
@ihabunek This also does not occur when I prevent the call to `curses.panel.update_panels()` in the Modal base class. I'm not sure exactly _why_ it works just fine without it, or more relevantly why `getch()` triggers this issue. Maybe it might have something to do with the automatic tty mode change that occurs?

I've got a [branch](https://github.com/Skehmatics/toot/tree/fix-100) containing that fix, but I'm hesitant to make a PR at this time until I better understand the root cause.

**Comment by Skehmatics** [comment]
Looks like it was much simpler, Modal's `__init__` was making changes to the panel stack (via `self.panel.hide()`) without also calling `curses.panel.update_panels()` before the next update call, likely mucking up the internal panels state. I've replaced that with the regular `Modal.hide()` method so that new subclasses don't start out with the same odd state.
