### ISSUE TITLE
Toot not available in Trisquel 8.0

### ISSUE THREAD

**Issue by RedStarfish** [ihabunek/toot#167]
I had been using Toot in Ubuntu for couple of month, but few days ago I moved to [Trisquel 8.0](https://trisquel.info). In Trisquel repositories Toot is not available. According to Toot's documentation one can install it using pip. But pip is not available in Trisquel either. So I tried to build it from souce: when I run `make` inside toot directory, I get this error:
```
python setup.py sdist --formats=gztar,zip
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
ImportError: No module named setuptools
Makefile:4: recipe for target 'dist' failed
make: *** [dist] Error 1
```
So from the above error it seemed setuptools was missing. So I installed `python3-setuptools`. But I still get the above error. Is there a way around this so that I can use Toot?

**Comment by ihabunek** [comment]
Firstly, I don't know much about Trisquel, but you most probably need to use `python3` instead of `python`. Secondly, if you just want to use toot, you don't need to build the source distribution package, which is what `sdist` does, you can just install toot by running:

```
python3 setup.py install --user
```
The `--user` option installs toot inside your home dir, more precisely `~/.local/bin/toot`so make sure that's in your path.

**Comment by RedStarfish** [comment]
Thank you for your help, it worked!
