### ISSUE TITLE
Custom LOCAL_DOMAIN instance setting isn't used

### ISSUE THREAD

**Issue by skerit** [ihabunek/toot#217]
My instance is running at `mastodon.elevenways.be`, but the `LOCAL_DOMAIN` has been set to just `elevenways.be`, while `WEB_DOMAIN` is set to `mastodon.elevenways.be`
Toot doesn't seem to use this, and just shows the full address:

![image](https://user-images.githubusercontent.com/755212/200874801-e9432875-8a0b-4ed0-8cd3-5ca5f13b6bd8.png)

**Comment by ruario** [comment]
Yeah I saw the same problem for users on http://social.vivaldi.net as their usernames end @vivaldi.net not @social.vivaldi.net

**Comment by ihabunek** [comment]
Looking into this.

@danschwarz  Regarding your fix, I'm working on something a bit more comprehensive.

Examining the v1 vs v2 instance endpoints:

* https://social.vivaldi.net/api/v1/instance
* https://social.vivaldi.net/api/v2/instance  (added in mastodon 4.0.0.)

Seems like v2 has `domain`, and v1 has `uri` but they both have the same value `vivaldi.net`. So this should be fine, we can determine the local domain for both older and newer mastodon instances.

I'll change the registration process, so that the correct domain name (in this case `vivaldi.net`) gets stored in the config file. We already store the base URL separately so this won't break anything.

**Comment by ruario** [comment]
I just upgraded (did the relogin as you suggested) and it works! Thanks again to you and of course @danschwarz
