### ISSUE TITLE
v0.30.1 sets missing keys to `null` instead of `None`, breaks Pleroma posting

### ISSUE THREAD

**Issue by rjp** [ihabunek/toot#250]
Just installed `toot` on a new machine and got v0.30.1 which proceeded not to be able to post to my Pleroma instance.  Had a look at the Elixir trace and it's coming from concatenating the status with the summary (spoiler text).  And yeah, it looks like v0.30.1 sets `spoiler_text` to `null` which confuses Pleroma.

```
rjp@box ~ $ toot post --debug TESTING --using account@instance
DEBUG:toot:>>> POST https://instance/api/v1/statuses
DEBUG:toot:>>> HEADERS: {('Authorization', '***CENSORED***'), ('User-Agent', 'toot/0.30.1'), ('Idempotency-Key', 'f2016e870c9f4c3285da7d27aa217372')}
DEBUG:toot:>>> JSON:    {"status": "TESTING", "media_ids": [], "visibility": "public", "sensitive": "false", "spoiler_text": null, "in_reply_to_id": null, "language": null, "scheduled_at": null}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): social.rjp.is:443
DEBUG:urllib3.connectionpool:https://social.rjp.is:443 "POST /api/v1/statuses HTTP/1.1" 500 45
DEBUG:toot:<<< <Response [500]>
DEBUG:toot:<<< {"errors":{"detail":"Internal server error"}}
Unknown error
```
For comparison, v0.28.0 sets anything unset to `None`,
```
rjp@otherbox$ toot post --debug TESTING
DEBUG:toot:>>> POST https://instance/api/v1/statuses
DEBUG:toot:>>> HEADERS: {('User-Agent', 'toot/0.28.0'), ('Authorization', '***CENSORED***'), ('Idempotency-Key', '14502fc39d7a46089be490b0006d6bed')}
DEBUG:toot:>>> DATA:    {'status': 'TESTING', 'media_ids[]': [], 'visibility': 'public', 'sensitive': 'false', 'spoiler_text': None, 'in_reply_to_id': None, 'language': None, 'scheduled_at': None}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): instance:443
DEBUG:urllib3.connectionpool:https://social.rjp.is:443 "POST /api/v1/statuses HTTP/1.1" 200 2678
[... etc ...]
```

I can work around this for now by setting the `spoiler_text` to empty (`-p ""`) but it's probably going to confuse some other people as well.

**Comment by rjp** [comment]
Double-checked to see if it was a Python 3.10 (otherbox) vs 3.11 (box) issue but v0.30.1 can't post without spoiler text on either version.

**Comment by ihabunek** [comment]
So the problem is not None vs null since these are equivalent - one is python and the other is json. I switched logging to show json-encoded data instead of dumping the python structure.

What I _did_ change, is that I'm sending the data as JSON instead of form-encoded. Because of this, the server gets `spoiler_text` set to null whereas it used to get an empty string (can't encode null in form-encoded data).

IMO this is a problem with Pleroma and should be reported, since [mastodon api](https://docs.joinmastodon.org/methods/statuses/#create) specifies that `spoiler_text` is not a required field.

That said, I'll fix this by passing an empty string instead of null so that Pleroma people can use toot.

**Comment by ihabunek** [comment]
I set up integration testing on pleroma and caught a couple more problems. Next release will fix those.

**Comment by rjp** [comment]
Ah, perfect, thanks, I'll flag it up on the Pleroma repo.
