### ISSUE TITLE
Support PPA for Ubuntu/Debian based distro

### ISSUE THREAD

**Issue by dtantono** [ihabunek/toot#459]
Hi
I know this client support debian based distro natively. But, the thing is the apt version is quite outdated compared to the current version and I think PPA is good. So, we can get faster updates. What do you think?

**Comment by ihabunek** [comment]
Sorry, but I don't have an interest in providing repos for various distros.

However, I can recommend that you install toot using [pipx](https://pipx.pypa.io/stable/). It is a python package manager which installs packages into separate virtual environments. Then you can `pipx upgrade toot` at any time to get the latest version from PyPI instead of waiting on your distro's packages.

**Comment by roughnecks** [comment]
Same issue but different purpose. I want to share toot to all users of a Debian stable host. Since the package is very old, can I do that using pipx?
