### ISSUE TITLE
[Feature request] Toot chaining

### ISSUE THREAD

**Issue by matthiasbeyer** [ihabunek/toot#464]
Hi,

from time to time I post chains of toots (where I reply to the latest toot again and again), because I have some long-form stuff to tell. You most likely have seen stuff like this already on the fediverse.

It would be really nice to be able to script these with `toot`, something like `toot post-chain --from-file ./file` to post each line as a seperate toot, replying to re previous one...

Or something more flexible even... I don't know. Maybe something to think about?

**Comment by ihabunek** [comment]
What about adding a flag like `--reply-last` which would make toot reply to the last posted toot on that instance?

**Comment by matthiasbeyer** [comment]
That sounds like a nice idea!

**Comment by Fipaddict** [comment]
Hi,
This issue seems to me to be a "Good first issue" and I'd like to try to implement it.

My idea is (on **post.py**) :
- add a `@click.option("--reply-last", is_flag=True, ....)` for _post(...)_ method
- create `_get_previous_post_id()` to set _reply_to_, but I don't know how to get previous post ID ? (like on CLI with a `toot timeline -a $ACCOUNT -1 -c 1`)

 Am I on the good way ? (and is there a helping hand for second point ?)

**Comment by danschwarz** [comment]
> What about adding a flag like `--reply-last` which would make toot reply to the last posted toot on that instance?

Seems like it would work most of time time, fail some of the time when others are posting toots simultaneously. 

`toot post --reply-to` should work more reliably, if you have your last posted toot's ID available.  Is it easy to retrieve this?  If not, perhaps making it easy to retrieve *your* last posted toot's ID is the best way forward.
