### ISSUE TITLE
Need document for `toot curses`

### ISSUE THREAD

**Issue by kakakaya** [ihabunek/toot#50]
I couldn't find document about curses in `toot curses -h` or README, but found it in source code.
https://github.com/ihabunek/toot/blob/c6b1d913707e9a107b44537e1f67dac73d82fe72/toot/ui/app.py#L344-L371

I propose to make document about curses, for better user experience.

**Comment by scrow** [comment]
Documentation is lacking for this entire project.  It's usually not that difficult for me to download some source files from Github, compile, and run, but I feel like I'm flying totally blind here.  All of the documentation is way too sparse.  Plenty of stuff to tell me what this project is supposed to do, nothing to tell me how to actually use it.

**Comment by ihabunek** [comment]
@scrow True. I started setting up [proper docs](https://toot.readthedocs.io/en/latest/), but it still requires a lot of work. Since this is a pet project, I can only invest so much time writing docs. 

Can you tell me what you're trying to do, and why it was hard to find out? Installation is documented, and the CLI commands are pretty well explained if you append `--help`. 

Finally, contributions are welcome (tm).

**Comment by ihabunek** [comment]
Basics explained here: https://toot.readthedocs.io/en/latest/usage.html#using-the-curses-ui
